######################################################################
# Automatically generated by qmake (3.0) Fri Jul 1 23:03:20 2016
######################################################################

TEMPLATE = app
TARGET = lShark
INCLUDEPATH += .
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
# Input


HEADERS += mainwindow.h \
    pkg_headers.h
SOURCES += main.cpp mainwindow.cpp
LIBS += /usr/lib64/libpcap.so


